vega/ts-json-schema-generator

package.json
src/TypeFormatter/IntersectionTypeFormatter.ts
src/TypeFormatter/ObjectTypeFormatter.ts
test/config/jsdoc-inheritance/schema.json
test/valid-data/generic-hell/schema.json
test/valid-data/type-aliases-local-namespace/main.ts
test/valid-data/type-aliases-local-namespace/schema.json
test/valid-data/type-intersection-additional-props/schema.json
test/valid-data/type-intersection/main.ts
test/valid-data/type-intersection/schema.json
yarn.lock

Do not generate definitions that are not needed. Fixes #18

---

src/NodeParser/AnyTypeNodeParser.ts
test/valid-data.test.ts
test/valid-data/any-unknown/main.ts
test/valid-data/any-unknown/schema.json

Closes vega/ts-json-schema-generator#56

add support for `unknown` type keyword

---

src/SchemaGenerator.ts
ts-json-schema-generator.ts

if we check non node_modules files first, we still get a significant speed up:
before: `12.93s user 0.68s system 137% cpu 9.862 total`
after: `12.22s user 0.67s system 139% cpu 9.248 total`

prioritize non node_modules

---

factory/index.ts
index.ts

can we have factory functions exported, it's useful if we want manually creating a generator?

Factory export

---

package.json
src/Schema/Definition.ts
src/Schema/RawType.ts
src/Schema/Schema.ts
src/TypeFormatter/AnnotatedTypeFormatter.ts
src/TypeFormatter/EnumTypeFormatter.ts
src/TypeFormatter/LiteralTypeFormatter.ts
src/TypeFormatter/LiteralUnionTypeFormatter.ts
src/TypeFormatter/PrimitiveUnionTypeFormatter.ts
src/Utils/allOfDefinition.ts
src/Utils/typeName.ts
yarn.lock

Use json schema type

---

src/NodeParser/AnnotatedNodeParser.ts
test/valid-data.test.ts
test/valid-data/class-jsdoc/main.ts
test/valid-data/class-jsdoc/schema.json

Fix parsing class property descriptions

---

factory/parser.ts
index.ts
src/NodeParser/PrefixUnaryExpressionNodeParser.ts
test/valid-data.test.ts
test/valid-data/generic-prefixed-number/main.ts
test/valid-data/generic-prefixed-number/schema.json

Don't know if there is any type construct which is allowed to use operands other than Minus but I implemented Plus, Tilde and Exclamation anyway.
Fixes #119

Implement support for prefix unary expressions

---

src/SchemaGenerator.ts

This was deliberately done in baby steps to make it more review-friendly. Feel free to squash into single (or fewer) commits if you prefer.

Refactor SchemaGenerator

---

factory/parser.ts
src/NodeParser/FunctionNodeParser.ts
src/Type/FunctionType.ts
test/valid-data.test.ts
test/valid-data/type-keyof-object-function/main.ts
test/valid-data/type-keyof-object-function/schema.json

Fixes https://github.com/vega/vega/pull/1698

Support function types in map values.

---

src/NodeParser/IndexedAccessTypeNodeParser.ts
test/valid-data.test.ts
test/valid-data/type-indexed-access-tuple-union/main.ts
test/valid-data/type-indexed-access-tuple-union/schema.json

Converts Tuple to union type when index is a number type

---

src/Utils/modifiers.ts
test/valid-data/class-single/main.ts
test/valid-data/class-single/schema.json
test/valid-data/interface-single/main.ts
test/valid-data/interface-single/schema.json

Fix isPublic function

---

README.md
src/Config.ts
src/SchemaGenerator.ts
src/TopRefNodeParser.ts
src/Type/DefinitionType.ts
test/valid-data.test.ts
test/valid-data/multiple-roots1/main.ts
test/valid-data/multiple-roots1/schema.json
test/valid-data/multiple-roots2/Asset.ts
test/valid-data/multiple-roots2/schema/AssetType.ts
test/valid-data/multiple-roots2/schema/MyAsset.ts
test/valid-data/multiple-roots2/schema/schema.json

Multiple Roots - complete implementation

---

src/NodeParser/TypeofNodeParser.ts
test/valid-data.test.ts
test/valid-data/keyof-typeof-enum/main.ts
test/valid-data/keyof-typeof-enum/schema.json
test/valid-data/type-typeof-enum/main.ts
test/valid-data/type-typeof-enum/schema.json

Implement enum support for typeof

---

src/NodeParser/TypeofNodeParser.ts
test/valid-data.test.ts
test/valid-data/keyof-typeof-enum/Size.ts
test/valid-data/keyof-typeof-enum/main.ts
test/valid-data/keyof-typeof-enum/schema.json

 Follow alias symbols in TypeofNodeParser 

---

src/Type/ObjectType.ts
src/TypeFormatter/ObjectTypeFormatter.ts
src/Utils/String.ts
test/unit/String.test.ts
test/valid-data.test.ts
test/valid-data/interface-property-dash/main.ts
test/valid-data/interface-property-dash/schema.json

Strip quotes from property names

---

src/NodeParser/MappedTypeNodeParser.ts
test/valid-data.test.ts
test/valid-data/type-mapped-enum-null/main.ts
test/valid-data/type-mapped-enum-null/schema.json
test/valid-data/type-mapped-enum-optional/main.ts
test/valid-data/type-mapped-enum-optional/schema.json
test/valid-data/type-mapped-enum/main.ts
test/valid-data/type-mapped-enum/schema.json

Add enum index signature support

---

src/Utils/allOfDefinition.ts
src/Utils/deepMerge.ts
test/unit/deepMerge.test.ts
test/valid-data.test.ts
test/valid-data/type-intersection-conflict/main.ts
test/valid-data/type-intersection-conflict/schema.json

Deep merge intersection properties

---

package.json

Move @types/json-schema to dependencies

---

test/config.test.ts
test/valid-data.test.ts

Closes #281 
ensures schemas generated in tests are fully validated against spec by AJV.
Will help prevent issues like #277

test: enable full AJV schema validation

---

src/TypeFormatter/ObjectTypeFormatter.ts
test/valid-data.test.ts
test/valid-data/generic-nested/main.ts
test/valid-data/generic-nested/schema.json

Adds support for the following:
`export interface MyObject extends Partial<IRequestParams<IRes>> { }`

Adds support for nested generics

---

src/SchemaGenerator.ts

Hey!
We are using ts-json-schema-generator programmatically and would like to be able to generate json schemas from `TS.Node`s that we locate ourselves via the AST.

expose #createSchemaFromNodes

---

README.md

- Addresses one task from #104 
- Adds info on CLI output path

Add info on programmatic usage

---

src/TypeFormatter/ObjectTypeFormatter.ts
src/Utils/allOfDefinition.ts
test/valid-data.test.ts
test/valid-data/type-extend-circular/main.ts
test/valid-data/type-extend-circular/schema.json

Fix: support extending circular reference

---

README.md

- Added options to Programmatic Usage to match the requirements.
- This closes #345

Add options to Programmatic Usage to match the requirements.

---

factory/generator.ts
src/SchemaGenerator.ts
test/config.test.ts
test/config/expose-all-topref-false-not-exported/main.ts
test/config/expose-all-topref-false-not-exported/schema.json
test/config/expose-all-topref-true-not-exported/main.ts
test/config/expose-all-topref-true-not-exported/schema.json

fix: generate types for unexported rootNodes when expose is set to all

---

README.md

Update README.md  typo

---

src/AnnotationsReader/ExtendedAnnotationsReader.ts
test/config/jsdoc-complex-extended/main.ts
test/config/jsdoc-complex-extended/schema.json

Fix newlines in description

---

src/NodeParser/CallExpressionParser.ts
test/valid-data-struct.test.ts
test/valid-data/object-function-expression/main.ts
test/valid-data/object-function-expression/schema.json

fix: function-expression as object value.

---

src/NodeParser/InterfaceAndClassNodeParser.ts
test/valid-data-struct.test.ts
test/valid-data/interface-computed-property-name/main.ts
test/valid-data/interface-computed-property-name/module.ts
test/valid-data/interface-computed-property-name/schema.json

feat: add support for computed property name

---

src/NodeParser/ObjectTypeNodeParser.ts
src/Type/ObjectType.ts
src/Utils/isAssignableTo.ts
test/unit/isAssignableTo.test.ts
test/valid-data-type.test.ts
test/valid-data/type-recursive-deep-exclude/main.ts
test/valid-data/type-recursive-deep-exclude/schema.json

feat: support deep exclude and correctly handle extending object
