vega/ts-json-schema-generator

README.md
factory/formatter.ts
src/Config.ts
src/Schema/Definition.ts
src/TypeFormatter/TupleTypeFormatter.ts
test/config.test.ts
test/config/strict-tuples-false/main.ts
test/config/strict-tuples-false/schema.json
test/config/strict-tuples-true/main.ts
test/config/strict-tuples-true/schema.json
ts-json-schema-generator.ts

With the `--strictTuples` option enabled, the generated schema does not allow for additional properties. 
See issue #28

add --strictTuples option: disallows additional elements in tuples

---

src/ExposeNodeParser.ts
test/config/expose-all-topref-false/main.ts
test/config/expose-all-topref-false/schema.json
test/config/expose-all-topref-true/main.ts
test/config/expose-all-topref-true/schema.json
test/config/expose-export-topref-false/main.ts
test/config/expose-export-topref-false/schema.json
test/config/expose-export-topref-true/main.ts
test/config/expose-export-topref-true/schema.json
test/config/expose-none-topref-false/main.ts
test/config/expose-none-topref-false/schema.json
test/config/expose-none-topref-true/main.ts
test/config/expose-none-topref-true/schema.json

Running `getFullyQualifiedName()` on an anonymous type literal returns `__type`. This causes all anonymous type literals to be exposed as `__type` in the schema file and overwrite each other.
```
type PrivateAnonymousTypeLiteral = {
privateValue: string;
};
```
Would be exported as a reference to:
```
"__type": {
"type": "object",
"properties": {
"privateValue": {
"type": "string"
}
},
"required": [
"privateValue"
],
"additionalProperties": false
}
```
This pull request prevents the exposing of anonymous type literals.

Anonymous type literals

---

src/SchemaGenerator.ts

Hi! Thanks for maintaining this great library.
We're running into a performance issue when generating schemas on a large codebase.
Our simplified usage pattern is:
```js
const program = createProgram(config);
const parser = createParser(program, config);
const formatter = createFormatter(config);
const g = new SchemaGenerator(program, parser, formatter);
const schemasToGenerate = [ ... ] // insert long array of type names here
schemasToGenerate.forEach((type) => generator.createSchema(type))
```
What we're seeing is that it takes about 11s to initialize the program, parser, formatter, and generator. Then it takes ~800ms for each schema we want to generate using the same instance of the generator.
Upon further investigation, we've found that `createSchema()` calls `findRootNode()`, which …

cache `allTypes` Map inside of SchemaGenerator instance

---

factory/program.ts
src/Config.ts

Hello again!
We're looking into schema generation performance again and we've found that skipping the type checking saves us a lot of time. In our flow, the actual TS to JS compilation does type checking, so we don't need the JSON schema generation to also do type checking.
Hope you find this useful as well. If you do, let me know what else I can do to get this merged! 😄

allow skipping of type checking to improve speed

---

test/config.test.ts

Hey, thanks for merging https://github.com/vega/ts-json-schema-generator/pull/50 😄 
What do you think of this for adding tests? I basically want to ensure that adding the `skipTypeCheck` option doesn't alter the output in any way. I chose `jsdoc-complex-extended` because it seemed to be the most complex case. Another option is to double up every test with `skipTypeCheck: true`, but that will significantly increase test time.

add test to ensure skipTypeCheck doesn't alter output

---

src/NodeParser/MappedTypeNodeParser.ts
test/valid-data.test.ts
test/valid-data/type-mapped-native-single-literal/main.ts
test/valid-data/type-mapped-native-single-literal/schema.json

Found a case where we use `Pick` with a single property and it was failing.

add support for mapped types with single property

---

README.md
factory/parser.ts
src/AnnotationsReader/BasicAnnotationsReader.ts
src/AnnotationsReader/ExtendedAnnotationsReader.ts
src/Config.ts
test/valid-data.test.ts
test/valid-data/annotation-custom/main.ts
test/valid-data/annotation-custom/schema.json
ts-json-schema-generator.ts

Add commandline option to parse additional terms from annotations and export them as json.
Similar to https://github.com/YousefED/typescript-json-schema --validationKeydords feature.
Can be used to provide "defaultSnippets" for monaco-editor (or vscode), etc.

Parse additional keywords from jsDoc annotations

---

src/ChainNodeParser.ts
src/CircularReferenceNodeParser.ts
src/ExposeNodeParser.ts
src/NodeParser.ts
src/NodeParser/AnnotatedNodeParser.ts
src/NodeParser/InterfaceNodeParser.ts
src/NodeParser/TypeAliasNodeParser.ts
src/NodeParser/TypeLiteralNodeParser.ts
src/Type/ReferenceType.ts
test/valid-data.test.ts
test/valid-data/type-aliases-recursive-generics-anonymous/main.ts
test/valid-data/type-aliases-recursive-generics-anonymous/schema.json
test/valid-data/type-aliases-recursive-generics-export/main.ts
test/valid-data/type-aliases-recursive-generics-export/schema.json

This PR fixes the problem with accessing the ID (and name) of a reference type before the reference type is actually created. This is done by adding an optional ReferenceType argument to NodeParser::createType(). The CircularReferenceNodeParser passes the created (and unfinished) ReferenceType via this argument to the actual node parser and each node parser can then decide if it wants to set the ID and name on the reference node before the actual type is created.
This fixes #45

Fix for id/name access before reference type is finished

---

src/Utils/typeKeys.ts
test/valid-data.test.ts
test/valid-data/type-indexed-access-object-2/schema.json
test/valid-data/type-mapped-optional/main.ts
test/valid-data/type-mapped-optional/schema.json

When property is optional then returned type must also allow undefined. So if not already a union type containing undefined a corresponding union type is now created and returned.
This fixes a problem with mapped types where the required-flag (when false) of an object property got lost (See unit test)
Also had to fix result of type-indexed-access-object-2 test. The output doesn't make much sense because it isn't possible to use undefined in JSON anyway but then the test itself may not make any sense because it actually uses an optional value as JSON root type.

Correct getTypeByKey()  for optional properties

---

src/NodeParser/InterfaceAndClassNodeParser.ts
test/valid-data.test.ts
test/valid-data/interface-array/main.ts
test/valid-data/interface-array/schema.json

This is actually a pretty special handling of a specific type of code. When an interface or a class extends Array or ReadonlyArray and nothing else and also does not add any properties then the type is parsed into an array instead of an object.
Fixes #83

Support types extending Array and ReadonlyArray

---

src/ChainNodeParser.ts
src/NodeParser.ts

This PR implements a cache for the types created by the ChainedNodeParser. Cache key is the ts.Node reference plus the current context state.
@domoritz With this change the vega-lite schema is created in 4 seconds on my system, no matter if Exclude-Types are used or not. But there is one strange problem: The generated JSON schema misses the type `RepeatSpec`. Everything else is exactly the same as before but this single type is missing. Do you know if there is something special about this type?

Cache created types for better speed

---

src/NodeParser/IndexedAccessTypeNodeParser.ts
src/NodeParser/MappedTypeNodeParser.ts
src/NodeParser/TypeOperatorNodeParser.ts
src/Utils/typeKeys.ts
test/valid-data.test.ts
test/valid-data/type-mapped-additional-props/main.ts
test/valid-data/type-mapped-additional-props/schema.json
test/valid-data/type-mapped-array/main.ts
test/valid-data/type-mapped-array/schema.json

Example:
```typescript
export interface Test {
[ name: string ]: string;
}
type WithNumbers<T> = {
[P in keyof T]: T[P] | number;
};
export type MyObject = WithNumbers<Test>;
```
Before this change the generated schema just described an empty object because the additional properties where ignored and not mapped. Now with this change the additional properties (if present) are also correctly mapped.

Support additional properties in mapped types

---

src/NodeParser/IndexedAccessTypeNodeParser.ts
test/valid-data.test.ts
test/valid-data/type-indexed-access-keyof/main.ts
test/valid-data/type-indexed-access-keyof/schema.json

An alternative to PR #132. Instead of implementing just a workaround for union types which only contain one type this solution actually handles union types.
Fixes #131

Support union types for indexed access

---

src/NodeParser/AnnotatedNodeParser.ts
src/NodeParser/InterfaceAndClassNodeParser.ts
src/Utils/modifiers.ts
test/valid-data/class-jsdoc/main.ts
test/valid-data/class-jsdoc/schema.json
test/valid-data/class-single/main.ts
test/valid-data/class-single/schema.json

Handling parameter property declarations pretty much works the same as handling properties so with this change I first merge these parameters and the properties into a single array before they are filtered by the various criterias and then converted into ObjectProperty instances.
I also simplified this whole process a little bit by adding a few new utility functions.
Fixes #134

Handle parameter property declarations

---

src/Error/BaseError.ts
src/Error/DiagnosticError.ts
src/Error/LogicError.ts
src/Error/NoRootTypeError.ts
src/Error/UnknownNodeError.ts
src/Error/UnknownTypeError.ts

Project is targeting ES2017 so Error can be extended directly instead of faking error objects. As a result exceptions thrown in tests now yield the correct error message and stack trace.
To test this you could temporarily add this code to the top of  `TypeReferenceNodeParser#createType` for example:
```typescript
if (2 > 1) {
throw new LogicError("What the heck?");
}
```
Without the changes in this PR you get ugly errors like this:
```
valid-data › import-anonymous
3 | 
4 |     public constructor() {
> 5 |         this.callStack = new Error().stack;
|                          ^
6 |     }
7 | 
8 |     public get stack(): string {
at new BaseError (src/Error/BaseError.ts:5:26)
at new LogicError (src/Error/LogicError.ts:5:9)
at TypeReferenceNodeParser.createType …
```

Improve exceptions

---

src/CircularReferenceTypeFormatter.ts

See https://github.com/vega/ts-json-schema-generator/pull/105#issuecomment-504742962. This significantly increases performance. 
In the future, `getChildren` should return a set. 
Fixes #2

de-duplicate children

---

src/Utils/isAssignableTo.ts
test/unit/isAssignableTo.test.ts

A last fix to finally get the schema in my own project fully working. Literal types were not properly supported in `isAssignableTo`

Fix literal type handling in isAssignableTo

---

src/NodeParser/ConditionalTypeNodeParser.ts
src/Type/UnionType.ts
src/Utils/uniqueTypeArray.ts
test/valid-data.test.ts
test/valid-data/type-conditional-narrowing/main.ts
test/valid-data/type-conditional-narrowing/schema.json

When check-type is a type parameter then we actually have to follow both branches with the check-type narrowed down by the extends-type (And the inverse of it) and then create a union type of all results. At least I hope that this finally gets it right now...
To prevent useless duplications in the resulting type I also improved the union type itself so it automatically flattens itself if possible, removes duplicate types and Never types. The new normalize() method can be used to convert it to the single type when only one is present or Never type if union is empty.
Fixes #148

Improve condition type node parser

---

src/NodeParser/TypeofNodeParser.ts

The expression typeof (type.getValue() === "number") is always truthy.

fix(TypeofNodeParser): correct type check

---

.prettierignore
.prettierrc.json
azure-pipelines.yml

I think the formatting prettier did to the `azure-pipelines.yml` file is what caused the deployment to be missed. This reverts it and stops prettier formatting it again.

Fix npm deployment

---

package.json

License not recognized by https://www.npmjs.com/package/ts-json-schema-generator
update the license syntax, see https://docs.npmjs.com/files/package.json#license

update package.json, set license

---

factory/formatter.ts
factory/parser.ts
src/NodeParser/VoidTypeNodeParser.ts
src/Type/VoidType.ts
src/TypeFormatter/VoidTypeFormatter.ts
src/Utils/isAssignableTo.ts
test/unit/isAssignableTo.test.ts
test/valid-data.test.ts
test/valid-data/generic-void/main.ts
test/valid-data/generic-void/schema.json

Thanks for the great tool! 
This adds a `VoidType(|Formatter|Parser)`.
Some background: 
I'm looking into https://github.com/microsoft/language-server-protocol/issues/67, basically reconciling the [reference implementation](https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.ts) types with the (separately maintained) [specification](https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-14.md). The good news: tsjsg handles the `protocol.ts` without complaint. Hooray :tada:! 
But... I've been running into a fair number of things that aren't getting pulled in to fully describe/validate what's in the markdown spec, and am having to expand my `--paths`, thereby encountering new issues. I assume it's failing …

Add void type

---

src/ExposeNodeParser.ts
test/config/jsdoc-complex-basic/schema.json
test/config/jsdoc-complex-extended/schema.json
test/config/jsdoc-complex-none/schema.json
test/valid-data/class-generics/schema.json
test/valid-data/generic-hell/schema.json
test/valid-data/generic-multiargs/schema.json
test/valid-data/generic-multiple/schema.json
test/valid-data/generic-prefixed-number/schema.json
test/valid-data/generic-recursive/schema.json
test/valid-data/generic-simple/schema.json
test/valid-data/generic-void/schema.json
test/valid-data/type-aliases-recursive-generics-export/schema.json
test/valid-data/type-conditional-inheritance/schema.json
test/valid-data/type-mapped-additional-props/schema.json
test/valid-data/type-mapped-generic/schema.json

This UriEncodes definition names to ensure compliance with JSON Schema spec.
Discussion is at https://github.com/vega/ts-json-schema-generator/pull/275

feat: encoding definition names

---

src/ExposeNodeParser.ts
src/TypeFormatter/DefinitionTypeFormatter.ts
src/TypeFormatter/ReferenceTypeFormatter.ts
test/config.test.ts
test/config/jsdoc-complex-basic/schema.json
test/config/jsdoc-complex-extended/schema.json
test/config/jsdoc-complex-none/schema.json
test/valid-data.test.ts
test/valid-data/class-generics/schema.json
test/valid-data/generic-hell/schema.json
test/valid-data/generic-multiargs/schema.json
test/valid-data/generic-multiple/schema.json
test/valid-data/generic-prefixed-number/schema.json
test/valid-data/generic-recursive/schema.json
test/valid-data/generic-simple/schema.json
test/valid-data/generic-void/schema.json
test/valid-data/type-aliases-recursive-generics-export/schema.json
test/valid-data/type-conditional-inheritance/schema.json
test/valid-data/type-mapped-additional-props/schema.json
test/valid-data/type-mapped-generic/schema.json

This PR fixes an issue to a previous PR #277 that encoded the definition names as well as the URI references. AJV expects definition names to be unencoded.
This also adds an AJV compile step to tests to detect issues like this.
Closes #285 and #283

fix: definition encoding

---

src/NodeParser/TypeofNodeParser.ts
test/valid-data.test.ts
test/valid-data/type-typeof-class/main.ts
test/valid-data/type-typeof-class/schema.json

* Previously would error out if you had a `typeof class`.
* Added a small change to TypeofNodeParser to handle the case of `typeof class`. I am *far* from certain that this is the correct modification, since I'm very much not familiar with the code base, but it seems to produce valid output, and for my purposes it unblocks my use of `ts-json-schema-generator` with objects that inherit from `Sequelize.Model`.
I verified that the test fails (with a LogicError) if my TypeofNodeParser modification isn't made, and that it succeeds after the else clause is restored. The only thing I don't feel qualified to judge is whether the schema output is _correct_ in a more robust sense; it "looks good to me," but as I say, I'm not sure that it's right and would appreciate more critical eyes to validate …

Support typeof class

---

src/Utils/allOfDefinition.ts
test/valid-data.test.ts
test/valid-data/interface-extended-extra-props/main.ts
test/valid-data/interface-extended-extra-props/schema.json

Fixes #325 
```
export interface MyObject extends StringMap {
param: string
}
export interface StringMap {
[key: string]: any
}
```
Will allow additionalProps

#325 Adds support for interface-extended-extra-props

---

src/SchemaGenerator.ts

Hi! Thanks for this useful tool.
This small change makes it possible to invoke `.createSchema()` with no arguments, whereas before omitting the argument required passing `.createSchema(undefined)`. This makes it more ergonomic.

Improve typing for `createSchema()`

---

README.md
factory/parser.ts
src/Config.ts
test/config.test.ts
test/utils.ts

This is another PR along the lines of #385.
The CLI has a few defaults which the programmatic interface doesn’t. I think it makes sense to harmonize these. In my use case, I’m using the CLi to generate the typings, and a test to check that they’re up to date. It would be better not to have to pass in these arguments (which I wasn’t even aware of when I was using the CLI).
Another way to implement this would be to create a MergedConfig type; happy to go that route if you’d prefer.
Looking forward to your feedback!

Make more of createParser’s config optional

---

src/NodeParser/IntersectionNodeParser.ts
src/NodeParser/TypeOperatorNodeParser.ts
src/Type/IntersectionType.ts
src/Type/UnionType.ts
src/Utils/preserveAnnotation.ts
src/Utils/removeUndefined.ts
src/Utils/typeKeys.ts
test/valid-data-type.test.ts
test/valid-data/type-indexed-access-type-union/main.ts
test/valid-data/type-indexed-access-type-union/schema.json
test/valid-data/type-intersection-union-primitive/main.ts
test/valid-data/type-intersection-union-primitive/schema.json

Fixes https://github.com/vega/ts-json-schema-generator/issues/446
`MyType` and `T` product correct types now. 
```ts
export type Foo = { foo: string } | { foo: number };
export type Bar = {
[P in keyof Foo]: Foo[P];
};
export type X = Bar & Foo;
export type MyType = X["foo"];
export type T = string & (number | string);
```

fix: correctly support indexed union

---

README.md
src/NodeParser/TypeReferenceNodeParser.ts
test/valid-data-type.test.ts
test/valid-data/type-date-annotation/main.ts
test/valid-data/type-date-annotation/schema.json
test/valid-data/type-date/main.ts
test/valid-data/type-date/schema.json
test/valid-data/type-regexp/main.ts
test/valid-data/type-regexp/schema.json

JS `Date` is represented as `{ "type": "string", "format": "date-time" }` in JSON Schema.
JS `RegExp` is represented as `{ "type": "string", "format": regex" }` in JSON Schema. 
Resolves #260

Add support for types Date and RegExp

---

factory/program.ts

Resolves #483.
Existing code deletes `declaration` tsconfig option, but leaves behind `declarationDir` and `declarationMap` which depend on `declaration` and cause typescript compilation failure if present.

Delete declarationDir and declarationMap from tsconfig

---

README.md
src/ExposeNodeParser.ts
src/NodeParser/EnumNodeParser.ts
src/NodeParser/HiddenTypeNodeParser.ts
src/SchemaGenerator.ts
src/Utils/hasJsDocTag.ts
src/Utils/isHidden.ts

Related to f716883
Currently, a type annotated as `@private` is inlined (i.e. it's not `$ref`erenced), but it's still included in the generated schema under a synthetic ID (e.g. `def-interface-1907173262-101-1186-1907173262-0-14381601989010`).

Fix `@private` and do some refactoring

---

README.md
factory/formatter.ts
index.ts
src/ChainTypeFormatter.ts
src/MutableTypeFormatter.ts
test/config.test.ts
test/config/custom-formatter-configuration/main.ts
test/config/custom-formatter-configuration/schema.json

Hi! 👋 
This is a proposal on how to enable customisation of the formatting step by adding the ability to add additional formatters programatically. In the example included in the test, a function type is formatted as a custom object defined by the consumer.
Example:
```ts
createFormatter(configuration, (formatter) => {
formatter.addTypeFormatter(new MyFunctionTypeFormatter())
})
```
I'm looking forward to your feedback!

feat:: configurable formatter

---

README.md
factory/formatter.ts
test/config.test.ts
test/config/custom-formatter-configuration-override/main.ts
test/config/custom-formatter-configuration-override/schema.json

Allow overriding built-in formatters by running the augmentor first.
Also a line of code that was missing from the readme.
Fixes #596

feat: allow overriding built-in formatters

---

README.md
src/Config.ts
src/SchemaGenerator.ts
test/utils.ts
test/valid-data-type.test.ts
test/valid-data/type-aliases-primitive-with-id/main.ts
test/valid-data/type-aliases-primitive-with-id/schema.json
ts-json-schema-generator.ts

Currently all schemas are generated without `$id`. This means if multiple of them are generated and used with `ajv`, there will be an error as `ajv` expects unique `$id` for each schema.
This adds an option to pass the id using CLI

add $id support

---

src/TypeFormatter/TupleTypeFormatter.ts
test/valid-data-other.test.ts
test/valid-data/array-max-items-optional/main.ts
test/valid-data/array-max-items-optional/schema.json
test/valid-data/array-min-items-1/main.ts
test/valid-data/array-min-items-1/schema.json
test/valid-data/array-min-items-2/main.ts
test/valid-data/array-min-items-2/schema.json
test/valid-data/array-min-max-items-optional/main.ts
test/valid-data/array-min-max-items-optional/schema.json
test/valid-data/array-min-max-items/main.ts
test/valid-data/array-min-max-items/schema.json

The type expression above can be used to indicate a uniform array with a minimum number of elements.
Prior to this change, output for the expression looks roughly as follows (schema references omitted for clarity):
```json
{
"type": "array",
"items": [
{
"type": "A"
},
{
"type": "A"
}
],
"minItems": 2,
"additionalItems": {
"type": "A"
}
}
```
While this is technically correct, and a direct translation of the input, it obscures intent.  It also causes a warning to be emitted in Ajv 7.x, see https://github.com/ajv-validator/ajv/issues/1417
With this change the output looks as below and doesn't generate a warning:
```json
{
"type": "array",
"items": {
"type": "A"
},
"minItems": 2,
}
```

feat: better output for idiom [A, A, ...A[]]

---

src/NodeParser/TypeOperatorNodeParser.ts
test/valid-data-other.test.ts
test/valid-data/shorthand-array/main.ts
test/valid-data/shorthand-array/schema.json

This will fix that a shorthand array type with the readonly modifier becomes a number type in JSON schema.
```ts
interface Type {
prop: readonly string[]
}
```
Closes https://github.com/vega/ts-json-schema-generator/issues/415

fix: fix shorthand array with readonly modifier

---

src/NodeParser/TupleNodeParser.ts
src/Type/TupleType.ts
src/Type/UnionType.ts
src/TypeFormatter/TupleTypeFormatter.ts
test/valid-data-type.test.ts
test/valid-data/type-extends-never/main.ts
test/valid-data/type-extends-never/schema.json

This PR addresses an issue where  `[T] extends [never]` always evaluates to true because the `never` type is removed from tuples.
I considered adding a `NeverType` but that is a bigger change affecting way more files.

feat: support "[T] extends [never]" check

---

README.md
factory/parser.ts
src/ChainNodeParser.ts
src/MutableParser.ts
test/config.test.ts
test/config/custom-formatter-configuration/custom-formatter-configuration-override/main.ts
test/config/custom-formatter-configuration/custom-formatter-configuration-override/schema.json
test/config/custom-parser-configuration-override/main.ts
test/config/custom-parser-configuration-override/schema.json
test/config/custom-parser-configuration/main.ts
test/config/custom-parser-configuration/schema.json

Hello again! 👋
Heres a proposal on how to allow customisation of the parsing step.
It follows the same pattern as the [previous update to formatters](https://github.com/vega/ts-json-schema-generator/pull/565) and allows the consumer to add parsing of unsupported types and to override the built-in parsers.

feat: Add ability to augment the parser

---

README.md

Trying this out and noticed a little typo in the path in the example usage.

chore: fix typo in path in example command line usage

---

src/TypeFormatter/AnnotatedTypeFormatter.ts
test/config/jsdoc-complex-extended/main.ts
test/config/jsdoc-complex-extended/schema.json

When using the `@asType` annotation on a complex type, a schema containing both a `$ref` and `type` attribute is generated, which is invalid.
The `@asType` annotation should take precedence over the `$ref` since this allows the user to override the detected type - e.g. when a property will be serialized to some other type.
This patch makes the generator behave consistently when using the `@asType` annotation on both simple and complex types.

fix: ensure @asType annotation overrides $ref

---

README.md
factory/parser.ts
src/NodeParser/FunctionParser.ts
src/NodeParser/ParameterParser.ts
src/SchemaGenerator.ts
test/config.test.ts
test/config/arrow-function-parameters/main.ts
test/config/arrow-function-parameters/schema.json
test/valid-data-other.test.ts
test/valid-data/function-parameters-default-value/main.ts
test/valid-data/function-parameters-default-value/schema.json
test/valid-data/function-parameters-jsdoc/main.ts
test/valid-data/function-parameters-jsdoc/schema.json
test/valid-data/function-parameters-optional/main.ts
test/valid-data/function-parameters-optional/schema.json
test/valid-data/function-parameters-required/main.ts
test/valid-data/function-parameters-required/schema.json

This PR adds support for parsing function parameters and exposing them in the JSON schema as `Parameter<typeof func>` ([issue 733](https://github.com/vega/ts-json-schema-generator/issues/733)). Please let me know if you see any problems with this naming, am open for suggestions.
I decided to represent the parameters as an object with the argument names as the property keys. You could argue it should be represented as an array instead but then you would lose the argument name (unless you use the JSON schema `title` property to represent the argument name, but not sure if that makes sense).
I tried to shoehorn my changes into the documentation, but not sure if I'm sure if it makes sense without making bigger documentation changes, I'd be happy to hear your thoughts on it!
With this PR …

feat: parameter type selector

---

src/SchemaGenerator.ts
test/config.test.ts
test/config/arrow-function-parameters/schema.json
test/valid-data-other.test.ts
test/valid-data/function-parameters-default-value/schema.json
test/valid-data/function-parameters-jsdoc/schema.json
test/valid-data/function-parameters-optional/schema.json
test/valid-data/function-parameters-required/schema.json

fix: Changed to use NamedParameters instead of Parameters for exported functions. #756

fix: rename Parameters to NamedParameters

---

README.md
factory/formatter.ts
test/config.test.ts
test/config/custom-formatter-configuration-circular/main.ts
test/config/custom-formatter-configuration-circular/schema.json

Closes #820.
I feel compelled to note that I'm fairly new to this project and even to TypeScript, but I don't feel like there was opportunity to do too much damage here :)  Maybe just double check that my explanations in the docs make sense.
Will happily make any amendments you suggest.

feat: support circular refs in custom formatters

---

package.json

As far as I can tell only these files were being covered by our lint script:
```
test/unit/AnnotatedTypeFormatter.test.ts
test/unit/String.test.ts
test/unit/deepMerge.test.ts
test/unit/intersectionOfArrays.test.ts
test/unit/isAssignableTo.test.ts
```
It should now cover all (but not the test fixtures, because I assume it we want it that way?)

fix: update the lint npm script to include all files in the test folder

---

src/NodeParser/FunctionParser.ts
test/config.test.ts
test/config/function-parameters-all/main.ts
test/config/function-parameters-all/schema.json
test/invalid-data.test.ts
test/invalid-data/function-parameters-declaration-missing-name/main.ts
test/invalid-data/function-parameters-declaration-missing-name/schema.json
test/valid-data-other.test.ts
test/valid-data/function-parameters-declaration/main.ts
test/valid-data/function-parameters-declaration/schema.json
test/valid-data/function-parameters-variable-assignment/main.ts
test/valid-data/function-parameters-variable-assignment/schema.json

fix Function node parser to return a `DefinitionType` instead of `ObjectType`
Also:
* Add logic to retrieve the name of the function
* Add (conservative) logic to try not get into a scenario where we cannot retrieve a function name
* Add test case for the specific issue (#793)
Should fix #793

fix: broken schema since v0.91
